[project]
name = "sumfor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
trial = [
    "jupyter>=1.1.1",
]
